export const DEFAULT_LIMITS = {
  MAX_LEVEL_ROLES: 10,
  MAX_RULE_PUNISHMENTS: 3,
};

export const PREMIUM_LIMITS = {
  MAX_LEVEL_ROLES: 20,
  MAX_RULE_PUNISHMENTS: 5,
};

export const DISCORD_KEYWORD_RULE_LIMIT = 6;
